name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for API
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: tastbaar/research-api
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./images/api
          file: ./images/api/Dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          cache-from: type=registry,ref=tastbaar/research-api:latest
          cache-to: type=inline


      - name: Extract metadata for Frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: tastbaar/research-frontend
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./images/frontend
          file: ./images/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=registry,ref=tastbaar/research-frontend:latest
          cache-to: type=inline
          build-args: |
            DOMAIN=tastbaar.studio



      - name: Extract metadata for Static
        id: meta-static
        uses: docker/metadata-action@v5
        with:
          images: tastbaar/research-static
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push Static image
        uses: docker/build-push-action@v5
        with:
          context: ./images/static
          file: ./images/static/Dockerfile
          push: true
          tags: ${{ steps.meta-static.outputs.tags }}
          labels: ${{ steps.meta-static.outputs.labels }}
          cache-from: type=registry,ref=tastbaar/research-static:latest
          cache-to: type=inline
